spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/giovanniDB
    username: devuser
    password: devpass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
server:
  port: 8081
